
export const TAG_NAME = 'TAG_NAME';
export const TAG_OBJECT_STORAGE = 'TAG_OBJECT_STORAGE';
export const TAG_AUTH_STATUS = 'TAG_AUTH_STATUS';
export const TAG_FAVOURITE_LIST = 'TAG_FAVOURITE_LIST';
export const TAG_RESERVATIONS = 'TAG_RESERVATIONS';
export const TAG_BLACKLIST = 'TAG_BLACKLIST';
export const PROFILE_IMAGE = 'PROFILE_IMAGE';
export const RESET_AUTH = 'RESET_AUTH';
export const ALL_USER_TAG_STORAGE = 'ALL_USER_TAG_STORAGE';
